namespace $.$$ {

	export class $bog_docs_guide extends $.$bog_docs_guide {

		@$mol_mem
		lesson_index() {
			const arg = this.$.$mol_state_arg.value( 'lesson' )
			if ( arg ) return Math.max( 0, parseInt( arg ) - 1 )
			return 0
		}

		current_lesson_data() {
			return this.lessons()[ this.lesson_index() ] ?? this.lessons()[ 0 ]
		}

		override current_title() {
			return this.current_lesson_data().title
		}

		override current_explanation() {
			return this.current_lesson_data().explanation
		}

		override current_task() {
			return this.current_lesson_data().task
		}

		override current_initial_code() {
			return this.current_lesson_data().initial_code
		}

		override current_solution() {
			return this.current_lesson_data().solution
		}

		@$mol_mem
		override Current_lesson() {
			const obj = super.Current_lesson()
			obj.hints = () => this.current_lesson_data().hints
			return obj
		}

		lessons() {
			const d = '$'
			return [

				{
					title: 'Welcome to ' + d + 'mol',
					explanation: [
						'# Getting Started',
						'',
						'Welcome to the interactive ' + d + 'mol guide. In this lesson you will create your first component.',
						'',
						'## Module Structure',
						'',
						'Every ' + d + 'mol module lives in its own folder:',
						'',
						'```',
						'my/hello/',
						'    hello.view.tree    \u2014 component layout',
						'    hello.view.ts      \u2014 component logic',
						'    hello.view.css.ts  \u2014 component styles',
						'```',
						'',
						'## view.tree Basics',
						'',
						'Components are declared in `.view.tree` files:',
						'',
						'```',
						d + 'my_hello ' + d + 'mol_view',
						'    sub /',
						'        \\Hello World!',
						'```',
						'',
						'- Class name starts with `' + d + '` and matches the folder path',
						'- `' + d + 'mol_view` is the simplest base component',
						'- `sub /` defines the list of child elements',
					].join( '\n' ),
					task: 'Create a component `' + d + 'my_hello` extending `' + d + 'mol_view` that displays **Hello World!**.',
					initial_code: '',
					solution: [
						d + 'my_hello ' + d + 'mol_view',
						'\tsub /',
						'\t\t\\Hello World!',
					].join( '\n' ),
					hints: [
						'Start with: `' + d + 'my_hello ' + d + 'mol_view`',
						'Add `sub /` on the next line (indented with a tab)',
						'Add `\\Hello World!` as a child (indented with two tabs)',
					],
				},

				{
					title: 'view.tree Syntax',
					explanation: [
						'# view.tree Syntax',
						'',
						'**view.tree** is the declarative language for describing UI components in ' + d + 'mol.',
						'',
						'## Component Declaration',
						'',
						'A component starts with its class name and the base class:',
						'',
						'```',
						d + 'my_hello ' + d + 'mol_view',
						'    sub /',
						'        \\Hello World!',
						'```',
						'',
						'- `' + d + 'my_hello` \u2014 your component class name',
						'- `' + d + 'mol_view` \u2014 base class to extend',
						'- `sub /` \u2014 list of child elements',
						'- `\\Hello World!` \u2014 raw text content',
						'',
						'## Nesting Components',
						'',
						'Use `<=` to declare named sub-components:',
						'',
						'```',
						d + 'my_app ' + d + 'mol_view',
						'    sub /',
						'        <= Title ' + d + 'mol_view',
						'            sub / \\Welcome',
						'        <= Button ' + d + 'mol_button_minor',
						'            sub / \\Click me',
						'```',
						'',
						'Each `<= Name ' + d + 'Component` creates a named property that returns a component instance.',
						'This is how you compose complex UIs from simple building blocks.',
						'',
						'## Indentation',
						'',
						'view.tree uses **tab indentation** to express nesting. Each nested level adds one more tab.',
					].join( '\n' ),
					task: [
						'Add a `' + d + 'mol_button_minor` named **Action** inside `' + d + 'my_app` below the existing text.',
						'',
						'The button should display text **"Click me"**.',
						'',
						'Use `<=` binding syntax to declare the button as a named property.',
					].join( '\n' ),
					initial_code: [
						d + 'my_app ' + d + 'mol_view',
						'\tsub /',
						'\t\t\\Click the button below',
					].join( '\n' ),
					solution: [
						d + 'my_app ' + d + 'mol_view',
						'\tsub /',
						'\t\t\\Click the button below',
						'\t\t<= Action ' + d + 'mol_button_minor',
						'\t\t\tsub /',
						'\t\t\t\t\\Click me',
					].join( '\n' ),
					hints: [
						'Use `<= Action ' + d + 'mol_button_minor` to add a named sub-component',
						'The button needs its own `sub /` with `\\Click me` inside',
						'Align `<= Action` at the same indent level as `\\Click the button below`',
					],
				},

				{
					title: 'Bindings',
					explanation: [
						'# Bindings in view.tree',
						'',
						'Bindings connect properties between components. There are three types:',
						'',
						'## One-way binding `<=`',
						'',
						'Reads a value from a property. The child **receives** data from the parent:',
						'',
						'```',
						d + 'my_app ' + d + 'mol_view',
						'    sub /',
						'        <= Title ' + d + 'mol_view',
						'            sub / <= title \\Hello',
						'```',
						'',
						'Here `<= title` reads the `title` property. The component displays its value.',
						'',
						'## Two-way binding `<=>`',
						'',
						'Creates a **synchronized** link between two properties. Changes flow in both directions:',
						'',
						'```',
						d + 'my_form ' + d + 'mol_view',
						'    sub /',
						'        <= Name_input ' + d + 'mol_string',
						'            value? <=> name? \\',
						'```',
						'',
						'When the user types in `Name_input`, the `name` property updates. If `name` changes elsewhere, the input updates too.',
						'',
						'The `?` after the property name means it accepts a new value (is writable).',
						'',
						'## Output binding `=>`',
						'',
						'Passes a property **out** to the parent. The child **provides** data:',
						'',
						'```',
						d + 'my_page ' + d + 'mol_page',
						'    title <= page_title \\My Page',
						'    body /',
						'        <= Content ' + d + 'mol_view',
						'            sub / <= page_title',
						'```',
						'',
						'## Common Pattern',
						'',
						'A typical pattern is connecting an input field to a label so they share the same value:',
						'',
						'```',
						d + 'my_greeting ' + d + 'mol_view',
						'    sub /',
						'        <= Input ' + d + 'mol_string',
						'            value? <=> user_name? \\World',
						'        <= Output ' + d + 'mol_view',
						'            sub / <= greeting \\',
						'```',
						'',
						'The `user_name` property is shared between the input and can be used elsewhere.',
					].join( '\n' ),
					task: [
						'Create a component `' + d + 'my_form` extending `' + d + 'mol_view` with:',
						'',
						'1. A `' + d + 'mol_string` input named **Name_input** with two-way binding `<=>` to property `name?` (default empty `\\`)',
						'2. A `' + d + 'mol_view` named **Greeting** that displays the `name` property via `<= name`',
						'',
						'Both should be children in `sub /`.',
					].join( '\n' ),
					initial_code: [
						d + 'my_form ' + d + 'mol_view',
						'\tsub /',
						'\t\t<= Name_input ' + d + 'mol_string',
						'\t\t<= Greeting ' + d + 'mol_view',
					].join( '\n' ),
					solution: [
						d + 'my_form ' + d + 'mol_view',
						'\tsub /',
						'\t\t<= Name_input ' + d + 'mol_string',
						'\t\t\tvalue? <=> name? \\',
						'\t\t<= Greeting ' + d + 'mol_view',
						'\t\t\tsub / <= name',
					].join( '\n' ),
					hints: [
						'Add `value? <=> name? \\` inside Name_input to create a two-way binding',
						'Add `sub / <= name` inside Greeting to read the name property',
						'The `?` after property names marks them as writable (accepting new values)',
					],
				},

				{
					title: 'Reactivity',
					explanation: [
						'# Reactivity with @' + d + 'mol_mem',
						'',
						'In ' + d + 'mol, every property is **automatically reactive**. This is powered by the `@' + d + 'mol_mem` decorator.',
						'',
						'## What @' + d + 'mol_mem Does',
						'',
						'When you declare a property in view.tree:',
						'',
						'```',
						d + 'my_app ' + d + 'mol_view',
						'    title \\Hello',
						'```',
						'',
						'The generated TypeScript code is:',
						'',
						'```typescript',
						'@' + d + 'mol_mem',
						'title() { return "Hello" }',
						'```',
						'',
						'`@' + d + 'mol_mem` gives every property three superpowers:',
						'',
						'1. **Memoization** — the value is computed once, then cached',
						'2. **Auto-tracking** — dependencies are tracked automatically',
						'3. **Lazy evaluation** — nothing computes until actually accessed',
						'',
						'## Auto-tracking in Action',
						'',
						'When two components share the same property, they stay in sync **automatically**:',
						'',
						'```',
						d + 'my_sync ' + d + 'mol_view',
						'    sub /',
						'        <= Editor ' + d + 'mol_string',
						'            value? <=> message? \\Hello',
						'        <= Display ' + d + 'mol_view',
						'            sub / <= message',
						'```',
						'',
						'- `message?` is a reactive state (writable because of `?`)',
						'- `Editor` writes to `message` through `<=>`',
						'- `Display` reads `message` through `<=`',
						'- When `message` changes → `Display` **automatically** re-renders',
						'',
						'No manual subscriptions. No event listeners. No `setState()`. The reactive system tracks everything.',
						'',
						'## Reactive Graph',
						'',
						'All reactive properties form a **dependency graph**. When a source property changes, only the properties that depend on it recompute. Everything else stays cached.',
						'',
						'This makes ' + d + 'mol apps very efficient — only what needs to update actually updates.',
					].join( '\n' ),
					task: [
						'Create a component `' + d + 'my_reactive` extending `' + d + 'mol_page` that demonstrates reactive state sharing.',
						'',
						'The page should have two `' + d + 'mol_string` inputs in the body:',
						'',
						'1. **Input** — with hint `\\Type something` and `value?` bound to `text?` (default empty `\\`)',
						'2. **Mirror** — with hint `\\Watch this update` and `value?` bound to the same `text?`',
						'',
						'Both inputs share the same reactive property, so typing in one instantly updates the other.',
					].join( '\n' ),
					initial_code: [
						d + 'my_reactive ' + d + 'mol_page',
						'\ttitle \\Reactivity Demo',
						'\tbody /',
						'\t\t<= Input ' + d + 'mol_string',
						'\t\t\thint \\Type something',
						'\t\t<= Mirror ' + d + 'mol_string',
						'\t\t\thint \\Watch this update',
					].join( '\n' ),
					solution: [
						d + 'my_reactive ' + d + 'mol_page',
						'\ttitle \\Reactivity Demo',
						'\tbody /',
						'\t\t<= Input ' + d + 'mol_string',
						'\t\t\thint \\Type something',
						'\t\t\tvalue? <=> text? \\',
						'\t\t<= Mirror ' + d + 'mol_string',
						'\t\t\thint \\Watch this update',
						'\t\t\tvalue? <=> text?',
					].join( '\n' ),
					hints: [
						'Both inputs need to share a common property via two-way binding `<=>`',
						'Add `value? <=> text? \\` on Input to create the writable `text` property with empty default',
						'Add `value? <=> text?` on Mirror to bind it to the same property (no default needed)',
					],
				},

				{
					title: 'Built-in Components',
					explanation: [
						'# Built-in Components',
						'',
						d + 'mol provides a rich set of ready-to-use components. Let\'s explore the most important ones.',
						'',
						'## ' + d + 'mol_page',
						'',
						'The standard page layout with a title bar, toolbar, and scrollable body:',
						'',
						'```',
						d + 'my_app ' + d + 'mol_page',
						'    title \\My App',
						'    tools /',
						'        <= Settings ' + d + 'mol_button_minor',
						'            sub / \\Options',
						'    body /',
						'        <= Content ' + d + 'mol_view',
						'            sub / \\Page content here',
						'```',
						'',
						'- `title` — text in the header bar',
						'- `tools /` — buttons/links in the top-right corner',
						'- `body /` — scrollable content area',
						'',
						'## Buttons',
						'',
						d + 'mol has two button styles:',
						'',
						'```',
						'<= Primary ' + d + 'mol_button_major',
						'    title \\Save',
						'',
						'<= Secondary ' + d + 'mol_button_minor',
						'    title \\Cancel',
						'```',
						'',
						'- `' + d + 'mol_button_major` — accented button for primary actions',
						'- `' + d + 'mol_button_minor` — subtle button for secondary actions',
						'- Both accept `click?` for handling clicks and `title` or `sub /` for content',
						'',
						'## ' + d + 'mol_form',
						'',
						'A structured form that groups input fields:',
						'',
						'```',
						d + 'my_settings ' + d + 'mol_form',
						'    form_fields /',
						'        <= Name ' + d + 'mol_string',
						'            value? <=> name? \\',
						'        <= Email ' + d + 'mol_string',
						'            value? <=> email? \\',
						'    buttons /',
						'        <= Submit ' + d + 'mol_button_major',
						'            title \\Save',
						'```',
						'',
						'- `form_fields /` — list of input components',
						'- `buttons /` — action buttons at the bottom',
						'',
						'## ' + d + 'mol_list',
						'',
						'A virtual list that efficiently renders large collections:',
						'',
						'```',
						'<= Items ' + d + 'mol_list',
						'    rows /',
						'        <= First ' + d + 'mol_view',
						'            sub / \\Item 1',
						'        <= Second ' + d + 'mol_view',
						'            sub / \\Item 2',
						'```',
						'',
						'`' + d + 'mol_list` only renders visible rows, making it performant even with thousands of items.',
					].join( '\n' ),
					task: [
						'Create a component `' + d + 'my_profile` extending `' + d + 'mol_page` with:',
						'',
						'1. Title set to `\\My Profile`',
						'2. A `' + d + 'mol_button_minor` named **Edit_btn** in `tools /` with `title \\Edit`',
						'3. A `' + d + 'mol_form` named **Form** in `body /` containing:',
						'    - A `' + d + 'mol_string` named **Name** with `value? <=> name? \\`',
						'    - A `' + d + 'mol_string` named **Email** with `value? <=> email? \\`',
					].join( '\n' ),
					initial_code: [
						d + 'my_profile ' + d + 'mol_page',
						'\ttitle \\My Profile',
					].join( '\n' ),
					solution: [
						d + 'my_profile ' + d + 'mol_page',
						'\ttitle \\My Profile',
						'\ttools /',
						'\t\t<= Edit_btn ' + d + 'mol_button_minor',
						'\t\t\ttitle \\Edit',
						'\tbody /',
						'\t\t<= Form ' + d + 'mol_form',
						'\t\t\tform_fields /',
						'\t\t\t\t<= Name ' + d + 'mol_string',
						'\t\t\t\t\tvalue? <=> name? \\',
						'\t\t\t\t<= Email ' + d + 'mol_string',
						'\t\t\t\t\tvalue? <=> email? \\',
					].join( '\n' ),
					hints: [
						'Add `tools /` with `<= Edit_btn ' + d + 'mol_button_minor` inside, and set `title \\Edit` on it',
						'Add `body /` with `<= Form ' + d + 'mol_form` inside, then add `form_fields /` to the form',
						'Inside `form_fields /` add two `' + d + 'mol_string` components with `value? <=> name? \\` and `value? <=> email? \\`',
					],
				},

				{
					title: 'Styling',
					explanation: [
						'# Styling with view.css.ts',
						'',
						'In ' + d + 'mol, styles are written in **TypeScript** using `' + d + 'mol_style_define`. This gives you full type-checking — no typos, no invalid values.',
						'',
						'## Basic Structure',
						'',
						'Every component can have a `*.view.css.ts` file:',
						'',
						'```typescript',
						'namespace ' + d + '.' + d + d + ' {',
						'    ' + d + 'mol_style_define(' + d + 'my_card, {',
						'        padding: ' + d + 'mol_gap.block,',
						'        background: {',
						'            color: ' + d + 'mol_theme.card,',
						'        },',
						'    })',
						'}',
						'```',
						'',
						'## Theme Tokens',
						'',
						'Use built-in theme tokens instead of hardcoded colors:',
						'',
						'| Token | Purpose |',
						'|---|---|',
						'| `' + d + 'mol_theme.back` | Page background |',
						'| `' + d + 'mol_theme.card` | Card background |',
						'| `' + d + 'mol_theme.text` | Main text |',
						'| `' + d + 'mol_theme.shade` | Muted text |',
						'| `' + d + 'mol_theme.accent` | Accent color |',
						'| `' + d + 'mol_theme.control` | Buttons/controls |',
						'| `' + d + 'mol_theme.field` | Input fields |',
						'',
						'And spacing tokens: `' + d + 'mol_gap.block` (standard padding), `' + d + 'mol_gap.round` (border-radius).',
						'',
						'## Styling Sub-components',
						'',
						'Target sub-components by their **property name** (PascalCase):',
						'',
						'```typescript',
						d + 'mol_style_define(' + d + 'my_card, {',
						'    Title: {',
						'        font: {',
						'            size: \'1.25rem\',',
						'            weight: \'bold\',',
						'        },',
						'        color: ' + d + 'mol_theme.text,',
						'    },',
						'    Description: {',
						'        color: ' + d + 'mol_theme.shade,',
						'    },',
						'})',
						'```',
						'',
						'The keys `Title` and `Description` match the property names from view.tree.',
						'',
						'## Key Rules',
						'',
						'1. **No `as any`** — if TypeScript complains, fix the format',
						'2. **No `rgba()`** — use hex: `\'#9c27b04d\'` instead of `rgba(156,39,176,0.3)`',
						'3. **No shorthand strings** for padding/margin: `padding: \'0.5rem 1rem\'` is wrong, use `padding: { top: \'0.5rem\', left: \'1rem\', ... }`',
						'4. Use `borderRadius` (camelCase) not `border: { radius }` for border-radius',
						'5. Sub-components are **top-level only** — no nesting `Icon` inside `Header`',
						'',
						'## Flex Layout',
						'',
						'```typescript',
						'flex: {',
						'    direction: \'column\',',
						'    wrap: \'wrap\',',
						'    grow: 1,',
						'},',
						'```',
						'',
						'Dark and light themes are supported **automatically** — theme tokens adapt to the current scheme.',
					].join( '\n' ),
					task: [
						'Create a component `' + d + 'my_card` extending `' + d + 'mol_view` with named sub-components:',
						'',
						'1. A `' + d + 'mol_view` named **Title** with `sub / \\My Card`',
						'2. A `' + d + 'mol_view` named **Description** with `sub / \\Card description text`',
						'',
						'These property names (`Title`, `Description`) would be targeted by `' + d + 'mol_style_define` in a real css.ts file.',
					].join( '\n' ),
					initial_code: [
						d + 'my_card ' + d + 'mol_view',
						'\tsub /',
						'\t\t\\My Card',
						'\t\t\\Card description text',
					].join( '\n' ),
					solution: [
						d + 'my_card ' + d + 'mol_view',
						'\tsub /',
						'\t\t<= Title ' + d + 'mol_view',
						'\t\t\tsub / \\My Card',
						'\t\t<= Description ' + d + 'mol_view',
						'\t\t\tsub / \\Card description text',
					].join( '\n' ),
					hints: [
						'Replace plain text with named sub-components using `<= Name ' + d + 'mol_view`',
						'`<= Title ' + d + 'mol_view` creates a named property that can be targeted by css.ts',
						'Each sub-component needs `sub / \\text` to hold its content',
					],
				},

				{
					title: 'Lists & Collections',
					explanation: [
						'# Lists & Collections',
						'',
						'In ' + d + 'mol, `*` is used for two purposes: **dictionaries** (key-value maps) and **multi-properties** (keyed component factories).',
						'',
						'## Dictionary `*`',
						'',
						'Use `*` to define a key-value map:',
						'',
						'```',
						'<= Lang ' + d + 'mol_select',
						'    value? <=> lang? \\en',
						'    dictionary *',
						'        en \\English',
						'        ru \\Russian',
						'        de \\German',
						'```',
						'',
						'`dictionary *` creates a static map `{ en: "English", ru: "Russian", de: "German" }`. Components like `' + d + 'mol_select` use this for option lists.',
						'',
						'## Multi-property `Item*`',
						'',
						'Adding `*` to a property name makes it **parameterized** — it creates one component instance per key:',
						'',
						'```',
						d + 'my_list ' + d + 'mol_list',
						'    rows /',
						'        <= Row* ' + d + 'mol_view',
						'            sub / <= row_title* \\',
						'```',
						'',
						'In TypeScript this generates:',
						'',
						'```typescript',
						'@' + d + 'mol_mem_key',
						'Row( id: any ) { return new ' + d + 'mol_view() }',
						'',
						'row_title( id: any ) { return "" }',
						'```',
						'',
						'The `*` suffix means the property takes an `id` parameter. Calling `Row("first")` returns one instance, `Row("second")` returns another.',
						'',
						'## Dynamic Lists',
						'',
						'To populate a list dynamically, override `rows()` in TypeScript:',
						'',
						'```typescript',
						'@' + d + 'mol_mem',
						'rows() {',
						'    return [ "buy_milk", "clean", "read" ].map(',
						'        id => this.Row( id )',
						'    )',
						'}',
						'',
						'@' + d + 'mol_mem_key',
						'row_title( id: string ) {',
						'    const titles: Record< string, string > = {',
						'        buy_milk: "Buy milk",',
						'        clean: "Clean house",',
						'        read: "Read book",',
						'    }',
						'    return titles[ id ] ?? id',
						'}',
						'```',
						'',
						'Each `Row(id)` is a separate component instance with its own lifecycle. ' + d + 'mol_list renders only the visible ones (virtual scrolling).',
						'',
						'## Key Point',
						'',
						'- `*` after a value = **dictionary** (key-value map)',
						'- `*` after a property name = **multi-property** (keyed factory)',
						'- Multi-properties generate `@' + d + 'mol_mem_key` in TypeScript',
						'- Use them with `' + d + 'mol_list` for efficient dynamic rendering',
					].join( '\n' ),
					task: [
						'Create a component `' + d + 'my_nav` extending `' + d + 'mol_view` with:',
						'',
						'1. `sub /` containing a `' + d + 'mol_list` named **Menu**',
						'2. The Menu has `rows /` with a multi-property `<= Row* ' + d + 'mol_button_minor`',
						'3. Each Row has `title <= row_title* \\`',
						'',
						'This creates a reusable navigation list where each `Row(id)` is a separate button.',
					].join( '\n' ),
					initial_code: [
						d + 'my_nav ' + d + 'mol_view',
						'\tsub /',
						'\t\t<= Menu ' + d + 'mol_list',
					].join( '\n' ),
					solution: [
						d + 'my_nav ' + d + 'mol_view',
						'\tsub /',
						'\t\t<= Menu ' + d + 'mol_list',
						'\t\t\trows /',
						'\t\t\t\t<= Row* ' + d + 'mol_button_minor',
						'\t\t\t\t\ttitle <= row_title* \\',
					].join( '\n' ),
					hints: [
						'Add `rows /` inside the Menu component to define its children',
						'Use `<= Row* ' + d + 'mol_button_minor` — the `*` makes it a multi-property (one button per key)',
						'Add `title <= row_title* \\` inside Row — the `*` on `row_title` matches the `*` on `Row`',
					],
				},

			{
				title: 'Navigation',
				explanation: [
					'# Navigation',
					'',
					d + 'mol provides built-in tools for page navigation and URL-based routing.',
					'',
					'## ' + d + 'mol_book2',
					'',
					d + 'mol_book2 is a multi-page container that stacks pages horizontally. It is the foundation for app navigation:',
					'',
					'```',
					d + 'my_app ' + d + 'mol_book2',
					'    pages /',
					'        <= Menu ' + d + 'mol_page',
					'            title \\Menu',
					'        <= Detail ' + d + 'mol_page',
					'            title \\Detail',
					'```',
					'',
					'On desktop, pages appear side by side. On mobile, they stack and only the top page is visible.',
					'',
					'## ' + d + 'mol_link',
					'',
					d + 'mol_link creates a link that **modifies URL arguments** instead of navigating to a new page:',
					'',
					'```',
					'<= Nav ' + d + 'mol_link',
					'    arg *',
					'        page \\about',
					'    sub / \\About',
					'```',
					'',
					'Clicking this link sets `#!page=about` in the URL hash. The page does **not** reload — only the arguments change reactively.',
					'',
					'## `arg *` Syntax',
					'',
					'`arg *` is a dictionary that maps argument names to values:',
					'',
					'```',
					'<= Home_link ' + d + 'mol_link',
					'    arg *',
					'        page \\home',
					'        tab \\main',
					'    sub / \\Home',
					'```',
					'',
					'This produces `#!page=home&tab=main` in the URL. Multiple arguments can be set at once.',
					'',
					'## ' + d + 'mol_state_arg',
					'',
					'To read arguments in TypeScript, use `' + d + 'mol_state_arg`:',
					'',
					'```typescript',
					'// Read the "page" argument from URL',
					'const page = this.' + d + '.' + d + 'mol_state_arg.value("page")',
					'```',
					'',
					'This is **reactive** — when the URL argument changes, any component reading it re-renders automatically.',
					'',
					'## Routing Pattern',
					'',
					'A common pattern: use `' + d + 'mol_link` in a menu and `' + d + 'mol_state_arg` in TypeScript to decide which pages to show:',
					'',
					'```',
					d + 'my_app ' + d + 'mol_book2',
					'    pages <= current_pages /',
					'```',
					'',
					'```typescript',
					'@' + d + 'mol_mem',
					'current_pages() {',
					'    const page = this.' + d + '.' + d + 'mol_state_arg.value("page")',
					'    switch (page) {',
					'        case "settings": return [ this.Menu(), this.Settings() ]',
					'        default: return [ this.Menu(), this.Home() ]',
					'    }',
					'}',
					'```',
					'',
					'The pages list updates reactively when the URL changes.',
				].join( '\n' ),
				task: [
					'Create a component `' + d + 'my_app` extending `' + d + 'mol_page` with:',
					'',
					'1. Title set to `\\My App`',
					'2. `tools /` containing two `' + d + 'mol_link` components:',
					'    - **Home_link** with `arg * page \\home` and `sub / \\Home`',
					'    - **Settings_link** with `arg * page \\settings` and `sub / \\Settings`',
					'',
					'These links modify URL arguments for navigation without a full page reload.',
				].join( '\n' ),
				initial_code: [
					d + 'my_app ' + d + 'mol_page',
					'\ttitle \\My App',
					'\ttools /',
				].join( '\n' ),
				solution: [
					d + 'my_app ' + d + 'mol_page',
					'\ttitle \\My App',
					'\ttools /',
					'\t\t<= Home_link ' + d + 'mol_link',
					'\t\t\targ *',
					'\t\t\t\tpage \\home',
					'\t\t\tsub / \\Home',
					'\t\t<= Settings_link ' + d + 'mol_link',
					'\t\t\targ *',
					'\t\t\t\tpage \\settings',
					'\t\t\tsub / \\Settings',
				].join( '\n' ),
				hints: [
					'Use `<= Home_link ' + d + 'mol_link` to create a named link component inside `tools /`',
					'Add `arg *` inside the link, then indent `page \\home` under it to set the URL argument',
					'Each link needs `sub / \\Text` to display its label',
				],
			},

			]
		}

	}

}
